name: mastodon_dart
description: The official Dart library for accessing the Mastodon API. Use in conjunction with mastodon_flutter to build a Flutter Mastodon app.
version: 0.4.0
homepage: https://github.com/lukepighetti/mastodon_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0
  rxdart: ^0.27.3
  web_socket_channel: ^2.1.0
  async: ^2.4.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  stack_trace: ^1.9.3
  test: ^1.14.2
